#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qtp_diversity import plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='source activate qtp-diversity')
@click.option('--ca-cert', prompt='Server certificate', default='None')
@click.argument('plugincoupling', required=False, default='filesystem')
def config(env_script, ca_cert, plugincoupling):
    """Generates the Qiita configuration files"""
    if ca_cert == 'None':
        ca_cert = None
    plugin.generate_config(env_script, 'start_diversity_types',
                           ca_cert, plugin_coupling=plugincoupling)


if __name__ == '__main__':
    config()
